<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/03/08 13:28:18
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
