<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
    use_helper('MbText');
    // use_javascript('lineup.js');
?>

<style>
div {
    /*width: 200px;
    height: 100px;*/
    overflow: auto;
}

</style>

<div class="page-header">
  <h2>CYBER</h2>
  <?php if(SF_DEBUG): ?>
    <?php echo link_to ('Add+', '@create_cyber') ?>
  <?php endif; ?>
</div>

<?php if(!$cybers): ?>

    <p>まだ何も登録していません。</p>

<?php else: ?>

    <?php foreach ($cybers as $key => $cyber): ?>
        <?php if($key % 3 == 0): ?>
            <div class="row-fluid">
                <ul class="thumbnails">
        <?php endif; ?>

            <li class="span4 item">
                <div class="thumbnail">
                    <?php echo $cyber->getImageTag('s','a',array('width'=>'260px','height'=>'150px')); ?>
                    <div class="caption">
                        <h3><?php echo $cyber->__toString(); ?></h3>
                        <p>
                            <?php echo mb_truncate_text($cyber->getSummary(),"48"); ?>
                        </p>
                    </div>
                    <div class="widget-footer">
                        <p>
                            &nbsp;
                            <!-- <a href="product.html" class="btn">Read more</a> -->
                            <?php echo link_to("Read more","@cyber?cyber_id=".$cyber->getId()); ?>
                        </p>
                    </div>
                </div>
            </li>

        <?php if($key % 3 == 3): ?>
                </ul>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

<?php endif; ?>

<script>

    // $(".item").lineUp();
    // $(".item").lineUp({
    //     onFontResize : false,
    //     onResize : true
    // });

</script>



