
cyber_list:
  url:   /cyber/list
  param: { module: cyber, action: list }

film_list:
  url:   /film/list
  param: { module: film, action: list }

press_list:
  url:   /press/list
  param: { module: press, action: list }


# default rules
homepage:
  url:   /
  param: { module: cyber, action: list }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
