
product_category_list:
  url:   /list/:category
  param: { module: product, action: list }

product:
  url:   /product/:product_id
  param: { module: product, action: show }

edit_product:
  url:   /edit/:product_id/:category
  param: { module: product, action: edit }

update_product:
  url:   /update/:category
  param: { module: product, action: update }

create_product:
  url:   /create/:category
  param: { module: product, action: create }

# default rules
homepage:
  url:   /
  param: { module: top, action: list }


default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
