<?php
    // auto-generated by sfPropelCrud
    // date: 2014/03/08 06:29:38
    use_helper('MbText');
?>

<head>
    <meta name="og:site_name" content="MapsTD" />
    <meta name="og:url" content="http://cannes.tyupakabura.com/" />
    <meta name="og:image" content="<?php $product->getImageTagPath("m") ?>"/>
    <meta name="og:type" content="website" />
    <meta name="og:title" content="<?php $product->getTitle() ?>" />
    <meta name="og:description" content="<?php $product->getSummary() ?>"/>
</head>

<div class="page-header">
    <h2><?php echo $product->getTitle() ?></h2>
    <?php if(SF_DEBUG): ?>
        <?php echo link_to('編集','@edit_product?product_id='.$product->getId().'&category='.$category) ?>
    <?php endif; ?>
    &nbsp;<?php echo link_to(strtoupper($category).'のTOP', '@product_category_list?category='.$category) ?>
</div>

<div>

    <div class="row-fluid">
        <?php if($category == "film" ): ?>

            <?php echo $product->getYoutubeTag(); ?>

        <?php elseif($category == "cyber"): ?>
            <div class="span12">
                <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="1000" height="800" align="middle">
                    <param name="allowScriptAccess" value="sameDomain" />
                    <param name="movie" value="/uploads/product/swf/swf_<?php echo $product->getId(); ?>a.swf" />
                    <param name="quality" value="autolow" />
                    <embed src="/uploads/product/swf/swf_<?php echo $product->getId(); ?>a.swf" quality="autolow" width="800" height="600" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
                </object>
            </div>
        <?php elseif($category == "press"): ?>



        <?php endif; ?>

    </div>

    <br><br>
    <div class="row-fluid">
        <h3>概要</h3>
        <p><?php echo autoLinker($product->getSummary()) ?></p>

        <h3>内容</h3>
        <p><?php echo autoLinker($product->getBody()) ?></p>

        <h3>感想</h3>
        <p><?php echo autoLinker($product->getImpression()) ?></p>

        <h3>メモ</h3>
        <p><?php echo autoLinker($product->getMemo()) ?></p>

    </div>

    <br><br>
    <div class="row-fluid">
        <table>
            <tbody>
                <tr>
                    <th>Title: </th>
                    <td><?php echo $product->getTitle() ?></td>
                </tr>
                <tr>
                    <th>Client: </th>
                    <td><?php echo $product->getClient() ?></td>
                </tr>
                <tr>
                    <th>Agency: </th>
                    <td><?php echo $product->getAgency() ?></td>
                </tr>
                <tr>
                    <th>Prize: </th>
                    <td><?php echo $product->getPrizeText(); ?></td>
                </tr>
                <tr>
                    <th>Url: </th>
                    <td><?php echo link_to($product->getUrl(),$product->getUrl(),array("target"=>"_blank")) ?></td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

