<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
?>
<?php

/**
 * civer actions.
 *
 * @package    youngcannes
 * @subpackage civer
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class pressActions extends sfActions
{
  public function executeList()
  {
    $this->presses = PressPeer::doSelect(new Criteria());

  }

  public function executeShow()
  {
    $this->press = PressPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->press);
  }

  public function executeCreate()
  {
    $this->press = new Press();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->press = PressPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->press);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $press = new Press();
    }
    else
    {
      $press = PressPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($press);
    }

    $press->setId($this->getRequestParameter('id'));
    $press->setTitle($this->getRequestParameter('title'));
    $press->setClient($this->getRequestParameter('client'));
    $press->setAgency($this->getRequestParameter('agency'));
    $press->setPrize($this->getRequestParameter('prize'));
    $press->setUrl($this->getRequestParameter('url'));
    $press->setYoutubeLink($this->getRequestParameter('youtube_link'));
    $press->setYoutubeTag($this->getRequestParameter('youtube_tag'));
    $press->setSummary($this->getRequestParameter('summary'));
    $press->setBody($this->getRequestParameter('body'));
    $press->setImpression($this->getRequestParameter('impression'));
    $press->setMemo($this->getRequestParameter('memo'));
    //displayを1にする。
    $press->setDisplay(1);
    //保存する。
    $press->save();

    //イメージ画像をいれる。
    $alphabet = str_split('abcde');
    $image_json = $press->getImage()?json_decode($press->getImage(),true): array();
    $yml_image_size = sfConfig::get('app_image_size');
    foreach ( $alphabet as $key1 => $value1)
    {
      $image_name = 'image_'.$press->getId().$value1;
      if($this->getRequest()->getFilePath('image_'.$value1))
      {
        foreach ($yml_image_size as $key2 => $value2)
        {
          $image = new sfThumbnail($value2['x'],$value2['y']);
          $image->loadFile($this->getRequest()->getFilePath('image_'.$value1));
          $image->save(sfConfig::get('sf_upload_dir').'/press/'.$key2.'/'.$image_name.'.jpg', 'image/jpeg');
        }
        $image_json['image_'.$value1] = $image_name;
      }
    }
    $press->setImage(json_encode($image_json));
    $press->save();

    return $this->redirect('press/show?id='.$press->getId());
  }

  //updateがエラーのとき
  public function handleErrorUpdate()
  {
    // if (!$this->getRequestParameter('id'))
    // {
    //   $civer = new Civer();
    // }
    // else
    // {
    //   $civer = CiverPeer::retrieveByPk($this->getRequestParameter('id'));
    //   $this->forward404Unless($civer);
    // }
    // $civer = new Civer();
    // // $civer->setId($this->getRequestParameter('id'));
    // $civer->setTitle($this->getRequestParameter('title'));
    // $civer->setClient($this->getRequestParameter('client'));
    // $civer->setAgency($this->getRequestParameter('agency'));
    // $civer->setUrl($this->getRequestParameter('url'));
    // $civer->setSummary($this->getRequestParameter('summary'));
    // $civer->setBody($this->getRequestParameter('body'));
    // $civer->setImpression($this->getRequestParameter('impression'));
    // $civer->setMemo($this->getRequestParameter('memo'));


    // $this->setTemplate('edit');
    // return sfView::SUCCESS;
  }

  public function executeDelete()
  {
    $press = PressPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($press);
    $press->setDisplay(0);
    $press->save();
    return $this->redirect('@press_list');
  }
}
