<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
?>
<?php use_helper('Object') ?>

<?php echo form_tag('civer/update') ?>

<?php echo object_input_hidden_tag($civer, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($civer, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Client:</th>
  <td><?php echo object_input_tag($civer, 'getClient', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Agency:</th>
  <td><?php echo object_input_tag($civer, 'getAgency', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Url:</th>
  <td><?php echo object_textarea_tag($civer, 'getUrl', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Summary:</th>
  <td><?php echo object_input_tag($civer, 'getSummary', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Body:</th>
  <td><?php echo object_textarea_tag($civer, 'getBody', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Impression:</th>
  <td><?php echo object_textarea_tag($civer, 'getImpression', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Memo:</th>
  <td><?php echo object_textarea_tag($civer, 'getMemo', array (
  'size' => '30x3',
)) ?></td>
</tr>
<tr>
  <th>Display:</th>
  <td><?php echo object_input_tag($civer, 'getDisplay', array (
  'size' => 7,
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($civer->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'civer/delete?id='.$civer->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'civer/show?id='.$civer->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'civer/list') ?>
<?php endif; ?>
</form>
