<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
?>
<div class="page-header">
  <h2>CIVER</h2>
  <?php echo link_to ('Add+', 'civer/create') ?>
</div>

<div class="row-fluid">
  <ul class="thumbnails">

    <li class="span4">
        <div class="thumbnail">
            <img src="" alt="">
            <div class="caption">
                <h3>Product name</h3>
                <p>
                    Few attractive words about your product.Few attractive words about your product.

                </p>
            </div>
            <div class="widget-footer">
                <p>
                    &nbsp;
                    <a href="product.html" class="btn">Read more</a>
                </p>
            </div>
        </div>
    </li>

    <li class="span4">
        <div class="thumbnail">
            <img src="" alt="">
            <div class="caption">
                <h3>Product name</h3>
                <p>
                    Few attractive words about your product.Few attractive words about your product.
                </p>
            </div>
            <div class="widget-footer">
                <p>
                    &nbsp;
                    <a href="product.html" class="btn">Read more</a>
                </p>
            </div>
        </div>
    </li>

    <li class="span4">
        <div class="thumbnail">
            <img src="" alt="">
            <div class="caption">
                <h3>Product name</h3>
                <p>
                    Few attractive words about your product.Few attractive words about your product.
                </p>
            </div>
            <div class="widget-footer">
                <p>
                    &nbsp;
                    <a href="product.html" class="btn">Read more</a>
                </p>
            </div>
        </div>
    </li>

  </ul>
</div>











