<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
?>
<h1>civer</h1>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Title</th>
  <th>Client</th>
  <th>Agency</th>
  <th>Url</th>
  <th>Summary</th>
  <th>Body</th>
  <th>Impression</th>
  <th>Memo</th>
  <th>Display</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($civers as $civer): ?>
<tr>
    <td><?php echo link_to($civer->getId(), 'civer/show?id='.$civer->getId()) ?></td>
      <td><?php echo $civer->getTitle() ?></td>
      <td><?php echo $civer->getClient() ?></td>
      <td><?php echo $civer->getAgency() ?></td>
      <td><?php echo $civer->getUrl() ?></td>
      <td><?php echo $civer->getSummary() ?></td>
      <td><?php echo $civer->getBody() ?></td>
      <td><?php echo $civer->getImpression() ?></td>
      <td><?php echo $civer->getMemo() ?></td>
      <td><?php echo $civer->getDisplay() ?></td>
      <td><?php echo $civer->getCreatedAt() ?></td>
      <td><?php echo $civer->getUpdatedAt() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'civer/create') ?>
