<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $civer->getId() ?></td>
</tr>
<tr>
<th>Title: </th>
<td><?php echo $civer->getTitle() ?></td>
</tr>
<tr>
<th>Client: </th>
<td><?php echo $civer->getClient() ?></td>
</tr>
<tr>
<th>Agency: </th>
<td><?php echo $civer->getAgency() ?></td>
</tr>
<tr>
<th>Url: </th>
<td><?php echo $civer->getUrl() ?></td>
</tr>
<tr>
<th>Summary: </th>
<td><?php echo $civer->getSummary() ?></td>
</tr>
<tr>
<th>Body: </th>
<td><?php echo $civer->getBody() ?></td>
</tr>
<tr>
<th>Impression: </th>
<td><?php echo $civer->getImpression() ?></td>
</tr>
<tr>
<th>Memo: </th>
<td><?php echo $civer->getMemo() ?></td>
</tr>
<tr>
<th>Display: </th>
<td><?php echo $civer->getDisplay() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $civer->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $civer->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'civer/edit?id='.$civer->getId()) ?>
&nbsp;<?php echo link_to('list', 'civer/list') ?>
