<?php
    // auto-generated by sfPropelCrud
    // date: 2014/03/08 06:29:38
    use_helper('MbText');
?>

<div class="page-header">
    <h2><?php echo $press->getTitle() ?></h2>
    <?php echo link_to('編集', 'press/edit?id='.$press->getId()) ?>
    &nbsp;<?php echo link_to('PRESSのTOP', '@press_list') ?>
</div>

<div>

    <?php if($press->getImageTag('l','a')): ?>
        <div class="row-fluid">
            <div class="span12">
                <?php echo $press->getImageTag('l','a'); ?>
            </div>
        </div>
        <br><br>
    <?php endif; ?>

    <?php if($press->getImageTag('l','b')): ?>
        <div class="row-fluid">
            <div class="span12">
                <?php echo $press->getImageTag('l','b'); ?>
            </div>
        </div>
        <br><br>
    <?php endif; ?>

    <?php if($press->getImageTag('l','c')): ?>
        <div class="row-fluid">
            <div class="span12">
                <?php echo $press->getImageTag('l','c'); ?>
            </div>
        </div>
        <br><br>
    <?php endif; ?>


    <div class="row-fluid">
        <h3>概要</h3>
        <p><?php echo autoLinker($press->getSummary()) ?></p>

        <h3>内容</h3>
        <p><?php echo autoLinker($press->getBody()) ?></p>

        <h3>感想</h3>
        <p><?php echo autoLinker($press->getImpression()) ?></p>

        <h3>メモ</h3>
        <p><?php echo autoLinker($press->getMemo()) ?></p>

    </div>

    <br><br>
    <div class="row-fluid">
        <table>
            <tbody>
                <tr>
                    <th>Title: </th>
                    <td><?php echo $press->getTitle() ?></td>
                </tr>
                <tr>
                    <th>Client: </th>
                    <td><?php echo $press->getClient() ?></td>
                </tr>
                <tr>
                    <th>Agency: </th>
                    <td><?php echo $press->getAgency() ?></td>
                </tr>
                <tr>
                    <th>Url: </th>
                    <td><?php link_to($press->getUrl(),$press->getUrl(),array("target"=>"_blank")) ?></td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

