<?php
    // auto-generated by sfPropelCrud
    // date: 2014/03/08 06:29:38
    use_helper('MbText');
?>

<div class="page-header">
    <h2><?php echo $film->getTitle() ?></h2>
    <?php echo link_to('編集', 'film/edit?id='.$film->getId()) ?>
    &nbsp;<?php echo link_to('FILMのTOP', '@film_list') ?>
</div>

<div>

    <div class="row-fluid">
        <div class="span12">
            <?php echo $film->getYoutubeTag() ?>
        </div>
    </div>

    <br><br>

    <div class="row-fluid">
        <div class="span4">
            <?php echo $film->getImageTag('m','a'); ?>
        </div>
        <div class="span4">
            <?php echo $film->getImageTag('m','b'); ?>
        </div>
        <div class="span4">
            <?php echo $film->getImageTag('m','c'); ?>
        </div>
    </div>

    <br><br>

    <div class="row-fluid">
        <h3>概要</h3>
        <p><?php echo autoLinker($film->getSummary()) ?></p>

        <h3>内容</h3>
        <p><?php echo autoLinker($film->getBody()) ?></p>

        <h3>感想</h3>
        <p><?php echo autoLinker($film->getImpression()) ?></p>

        <h3>メモ</h3>
        <p><?php echo autoLinker($film->getMemo()) ?></p>

    </div>

    <br><br>
    <div class="row-fluid">
        <table>
            <tbody>
                <tr>
                    <th>Title: </th>
                    <td><?php echo $film->getTitle() ?></td>
                </tr>
                <tr>
                    <th>Client: </th>
                    <td><?php echo $film->getClient() ?></td>
                </tr>
                <tr>
                    <th>Agency: </th>
                    <td><?php echo $film->getAgency() ?></td>
                </tr>
                <tr>
                    <th>Url: </th>
                    <td><?php echo link_to($film->getUrl(),$film->getUrl(),array("target"=>"_blank")) ?></td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

