<?php
// auto-generated by sfPropelCrud
// date: 2014/03/08 06:29:38
?>
<?php

/**
 * civer actions.
 *
 * @package    youngcannes
 * @subpackage civer
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class civerActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('civer', 'list');
  }

  public function executeList()
  {
    $this->civers = CiverPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->civer = CiverPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->civer);
  }

  public function executeCreate()
  {
    $this->civer = new Civer();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->civer = CiverPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->civer);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $civer = new Civer();
    }
    else
    {
      $civer = CiverPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($civer);
    }

    $civer->setId($this->getRequestParameter('id'));
    $civer->setTitle($this->getRequestParameter('title'));
    $civer->setClient($this->getRequestParameter('client'));
    $civer->setAgency($this->getRequestParameter('agency'));
    $civer->setUrl($this->getRequestParameter('url'));
    $civer->setSummary($this->getRequestParameter('summary'));
    $civer->setBody($this->getRequestParameter('body'));
    $civer->setImpression($this->getRequestParameter('impression'));
    $civer->setMemo($this->getRequestParameter('memo'));
    $civer->setDisplay($this->getRequestParameter('display'));

    $civer->save();

    return $this->redirect('civer/show?id='.$civer->getId());
  }

  public function executeDelete()
  {
    $civer = CiverPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($civer);

    $civer->delete();

    return $this->redirect('civer/list');
  }
}
